on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2

      - name: Go run maker
        run: go run maker.go

      - name: Go build maker
        run: go build maker.go

      - name: Go run auto
        run: go run auto.go

      - name: Go build auto
        run: go build auto.go

      - name: Create release with assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files:
            - maker
            - auto
